### ISSUE TITLE
Usage Error?

### ISSUE THREAD

**Issue by melissajhansen** [scolladon/sfdc-git-package#11]
I may be misunderstanding the usage for this tool.  When I run any of the following, I'm getting this error: events.js:183
      throw er; // Unhandled 'error' event

I've tried leaving out arguments that should have defaults, but still only getting back that error message.  Can you provide a sample command that would generate a package?

Attempted usages:

sgp -t dedeb392bda33507f390095e3d08463235976712 -f 3ef855215f5b4536be7ee89c59cb32591c0c9517

sgp -t dedeb392bda33507f390095e3d08463235976712 -f 3ef855215f5b4536be7ee89c59cb32591c0c9517 -o manifest/temp.xml -a 45.0

sgp -t dedeb392bda33507f390095e3d08463235976712 -f 3ef855215f5b4536be7ee89c59cb32591c0c9517 -o manifest -a 45.0

sgp -t dedeb392bda33507f390095e3d08463235976712 -f 3ef855215f5b4536be7ee89c59cb32591c0c9517 -o manifest -a 45.0 -r StandForChildren/SFDC

**Comment by sudhirtataraju** [comment]
Same error for me also:

-bash-4.2$ sgp -f 0bf19eef3fe419f5815a2755e6d857df79565013 -t faa4cc5eee413069821e49866d3bddd4e80465b9 -o config/ -a 48.0
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

@scolladon  please help giving an example

**Comment by scolladon** [comment]
what is the your node version and environment ?

**Comment by sudhirtataraju** [comment]
@scolladon  

npm --version
6.13.7

Linux Environment

**Comment by melissajhansen** [comment]
@scolladon  I'm on npm 6.4.1 on a Mac
